<?php

return [
    'db_file' => __DIR__ . '/../database/summer.db',
    'upload_dir' => __DIR__ . '/../public/uploads',
    'app_version' => '1.1.1',
    'public_base_path' => getenv('PUBLIC_BASE_PATH') ?: '/lich-he-test',
    'max_upload_size' => 5 * 1024 * 1024,
    'allowed_upload_types' => [
        'image/jpeg' => 'jpg',
        'image/png' => 'png',
        'image/webp' => 'webp',
    ],
    'parent_password' => getenv('PARENT_PASSWORD') ?: '1234',
    'activity_categories' => [
        'study' => 'Học tập',
        'reading' => 'Đọc sách',
        'writing' => 'Viết lách',
        'exercise' => 'Vận động',
        'creative' => 'Sáng tạo',
        'housework' => 'Việc nhà',
        'plant_fish' => 'Cây & cá',
        'screen_penalty' => 'Trừ sao màn hình',
        'bonus' => 'Thưởng thêm',
        'other' => 'Khác',
    ],
    'activity_options' => [
        'study_2h' => ['Học ban ngày 2 giờ (T2-T6)', 2, 'study'],
        'read_book' => ['Đọc sách', 1, 'reading'],
        'copy_sutra' => ['Chép kinh', 1, 'writing'],
        'write_story' => ['Viết truyện', 1, 'writing'],
        'journal' => ['Viết nhật ký', 1, 'writing'],
        'exercise' => ['Tập thể dục / vận động', 1, 'exercise'],
        'creative' => ['Vẽ tranh / sáng tạo', 1, 'creative'],
        'housework' => ['Việc nhà được giao', 1, 'housework'],
        'water_plant' => ['Tưới cây / chăm cây', 1, 'plant_fish'],
        'feed_fish' => ['Cho cá ăn / chăm bể cá', 1, 'plant_fish'],
        'clean_room' => ['Dọn bàn học, phòng ngủ', 1, 'housework'],
        'screen_ok' => ['Không vượt thời gian màn hình', 1, 'bonus'],
    ],
    'penalty_options' => [
        0 => ['Không vượt giờ / không chơi quá quy định', 0],
        60 => ['Chơi 1 giờ YouTube/TV/Game', -3, 'screen_penalty'],
        120 => ['Chơi 2 giờ YouTube/TV/Game', -10, 'screen_penalty'],
    ],
    'quick_actions' => [
        'study_2h' => ['Học 2h', 2, 'study'],
        'read_book' => ['Đọc sách', 1, 'reading'],
        'copy_sutra' => ['Chép kinh', 1, 'writing'],
        'write_story' => ['Viết truyện', 1, 'writing'],
        'exercise' => ['Tập thể dục', 1, 'exercise'],
        'draw_picture' => ['Vẽ tranh', 1, 'creative'],
        'housework' => ['Việc nhà', 1, 'housework'],
        'water_plant' => ['Tưới cây', 1, 'plant_fish'],
        'feed_fish' => ['Cho cá ăn', 1, 'plant_fish'],
        'screen_1h' => ['Chơi 1h', -3, 'screen_penalty'],
        'screen_2h' => ['Chơi 2h', -10, 'screen_penalty'],
    ],
    'reward_options' => [
        'Hoạt động gia đình' => 20,
        '1 quyển truyện' => 25,
        '1 cây nhỏ' => 25,
        'Phần thưởng tự chọn bất kỳ' => 35,
        'Về ngủ chơi nhà bà nội' => 50,
    ],
];
